import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getCurrentUser, hasAnyRole } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { buildMatches } from '@/lib/matching';
const schema=z.object({ticketId:z.string().min(1),action:z.enum(['APPROVE','NEEDS_INFO','REJECT']),note:z.string().trim().max(2000).optional().default('')});
export async function POST(req:Request){const user=await getCurrentUser();if(!user||!hasAnyRole(user.roles,['MODERATOR','ADMIN']))return NextResponse.json({error:'دسترسی ندارید.'},{status:403});const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:'درخواست نامعتبر است.'},{status:400});const t=await prisma.ticket.findUnique({where:{id:parsed.data.ticketId}});if(!t)return NextResponse.json({error:'مسئله پیدا نشد.'},{status:404});
  if(parsed.data.action==='APPROVE'){const matches=await buildMatches({domain:t.domain,city:t.city});await prisma.$transaction([prisma.ticket.update({where:{id:t.id},data:{status:'MATCHED',moderatorNote:parsed.data.note||null}}),prisma.matchingRequest.upsert({where:{ticketId:t.id},update:{suggestedExperts:matches},create:{ticketId:t.id,suggestedExperts:matches,autoMatchFlag:true}}),prisma.notification.create({data:{userId:t.userId,type:'TICKET_MATCHED',payload:{ticketId:t.id,count:matches.length}}}),prisma.auditLog.create({data:{actorId:user.id,action:'APPROVE_TICKET',entityType:'Ticket',entityId:t.id,metadata:{matchCount:matches.length}}})]);return NextResponse.json({ok:true,matches});}
  const status=parsed.data.action==='NEEDS_INFO'?'NEEDS_INFO':'REJECTED';await prisma.$transaction([prisma.ticket.update({where:{id:t.id},data:{status,moderatorNote:parsed.data.note||null}}),prisma.notification.create({data:{userId:t.userId,type:status,payload:{ticketId:t.id,note:parsed.data.note}}}),prisma.auditLog.create({data:{actorId:user.id,action:status,entityType:'Ticket',entityId:t.id}})]);return NextResponse.json({ok:true});}
