import Link from 'next/link';
import { IconGlyph } from './IconGlyph';
import { TICKET_STATUS } from '@/lib/constants';

type Section=any;
export function HomeRenderer({sections,user,experts,experiences,tickets,categories}:{sections:Section[];user:any;experts:any[];experiences:any[];tickets:any[];categories:any[]}){
  return <>{sections.map(section=>{
    if(section.type==='quick_actions') return <div className="quick-grid cms-grid" style={{['--cols' as any]:section.columnsDesktop,['--mcols' as any]:section.columnsMobile}} key={section.id}>{section.items.map((i:any)=><Link key={i.id} href={i.linkUrl||'#'} className="quick-card">{i.imageUrl?<img className="cms-icon-img" src={i.imageUrl} alt=""/>:<div className="qicon"><IconGlyph icon={i.icon}/></div>}<b>{i.title}</b>{i.subtitle&&<small>{i.subtitle}</small>}</Link>)}</div>;
    if(section.type==='hero') return <section key={section.id} className="hero cms-hero" style={section.backgroundUrl?{backgroundImage:`linear-gradient(135deg,rgba(4,57,66,.88),rgba(15,138,128,.78)),url(${section.backgroundUrl})`}:undefined}>{section.eyebrow&&<div className="eyebrow">{section.eyebrow}</div>}<h2>{section.title}</h2>{section.body&&<p>{section.body}</p>}<div className="hero-actions">{section.primaryLabel&&<Link className="btn btn-primary" href={section.primaryUrl||'#'}>{section.primaryLabel}</Link>}{section.secondaryLabel&&<Link className="btn btn-ghost" href={section.secondaryUrl||'#'}>{section.secondaryLabel}</Link>}</div></section>;
    if(section.type==='user_tickets'){if(!user||!tickets.length)return null; return <section className="section" key={section.id}><div className="section-head"><div className="section-title">{section.title}</div><Link href={section.primaryUrl||'/issues'}>{section.primaryLabel||'مشاهده همه'}</Link></div><div className="panel">{tickets.map(t=><Link key={t.id} href="/issues" className="list-item"><div className="list-icon">?</div><div><b>{t.title}</b><small>{t.domain} · {new Intl.DateTimeFormat('fa-IR').format(t.createdAt)}</small></div><span className="status blue">{TICKET_STATUS[t.status]||t.status}</span></Link>)}</div></section>}
    if(section.type==='categories') return <section className="section" key={section.id}><div className="section-head"><div><div className="section-title">{section.title}</div>{section.subtitle&&<div className="small muted">{section.subtitle}</div>}</div></div><div className="cat-grid cms-grid" style={{['--cols' as any]:section.columnsDesktop,['--mcols' as any]:section.columnsMobile}}>{categories.map(c=><Link key={c.id} href={'/knowledge?domain='+encodeURIComponent(c.name)} className="cat">{c.imageUrl?<img className="cms-icon-img" src={c.imageUrl} alt=""/>:<div className="ci"><IconGlyph icon={c.icon}/></div>}<span>{c.name}</span></Link>)}</div></section>;
    if(section.type==='experts') return <section className="section" key={section.id}><div className="section-head"><div><div className="section-title">{section.title}</div>{section.subtitle&&<div className="small muted">{section.subtitle}</div>}</div><Link href={section.primaryUrl||'/experts'}>{section.primaryLabel||'مشاهده همه'}</Link></div><div className="h-scroll">{experts.map(e=><div key={e.id} className="advisor-card"><div className="advisor-head">{e.user.avatarUrl?<img className="avatar avatar-img" src={e.user.avatarUrl} alt={e.user.name||''}/>:<div className="avatar">👤</div>}<div><h3>{e.user.name}</h3><span className="verified">تأیید شبکه</span><div className="advisor-sub">{e.headline}</div></div></div><div className="tags">{e.tags.slice(0,3).map((t:string)=><span key={t} className="tag">{t}</span>)}</div><div className="advisor-meta"><span>{e.yearsExperience} سال تجربه</span><span>{e.experienceCount} تجربه ثبت‌شده</span></div><Link className="btn btn-solid block" href={'/experts/'+e.id}>مشاهده و رزرو</Link></div>)}</div></section>;
    if(section.type==='knowledge') return <section className="section" key={section.id}><div className="section-head"><div><div className="section-title">{section.title}</div>{section.subtitle&&<div className="small muted">{section.subtitle}</div>}</div><Link href={section.primaryUrl||'/knowledge'}>{section.primaryLabel||'همه تجربه‌ها'}</Link></div><div className="article-grid cms-grid" style={{['--cols' as any]:section.columnsDesktop,['--mcols' as any]:section.columnsMobile}}>{experiences.map(x=><Link key={x.id} href={'/knowledge/'+x.id} className="article"><div className="article-img" style={x.coverImageUrl?{backgroundImage:`url(${x.coverImageUrl})`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}/><div className="article-body"><b>{x.title}</b><small>{x.domain} · تجربه میدانی</small></div></Link>)}</div></section>;
    if(section.type==='cards'||section.type==='faq'||section.type==='courses') return <section className="section" key={section.id}><div className="section-head"><div><div className="section-title">{section.title}</div>{section.subtitle&&<div className="small muted">{section.subtitle}</div>}</div>{section.primaryLabel&&<Link href={section.primaryUrl||'#'}>{section.primaryLabel}</Link>}</div><div className="cms-card-grid cms-grid" style={{['--cols' as any]:section.columnsDesktop,['--mcols' as any]:section.columnsMobile}}>{section.items.map((i:any)=><Link href={i.linkUrl||'#'} key={i.id} className="panel cms-item-card">{i.imageUrl&&<img src={i.imageUrl} alt={i.title}/>}<div className="cms-item-title">{i.icon&&<IconGlyph icon={i.icon}/>}<b>{i.title}</b></div>{i.subtitle&&<div className="small muted">{i.subtitle}</div>}{i.body&&<p className="small">{i.body}</p>}{i.badge&&<span className="tag">{i.badge}</span>}{i.linkLabel&&<div className="cms-item-link">{i.linkLabel} ←</div>}</Link>)}</div></section>;
    if(section.type==='cta') return <section className="section" key={section.id}><div className="panel cms-cta">{section.imageUrl&&<img src={section.imageUrl} alt=""/>}<div><h3>{section.title}</h3>{section.body&&<p className="small muted">{section.body}</p>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{section.primaryLabel&&<Link className="btn btn-outline" href={section.primaryUrl||'#'}>{section.primaryLabel}</Link>}{section.secondaryLabel&&<Link className="btn btn-solid" href={section.secondaryUrl||'#'}>{section.secondaryLabel}</Link>}</div></div></div></section>;
    return null;
  })}</>
}
